import { Injectable } from '@angular/core';
import { Todo } from './todo.model';

@Injectable({
  providedIn: 'root',
})
export class TodosService {
  todos: Todo[] = [
    {
      id: 1,
      user_id: 1,
      title: 'Finish project proposal',
      description: 'Complete the final draft and send to the client for review.',
      due_date: '2025-01-10',
      priority: 'high',
      is_completed: false,
      category: 'work',
    },
    {
      id: 2,
      user_id: 1,
      title: 'Book car service',
      description: 'Schedule MOT and annual service.',
      due_date: '2025-01-15',
      priority: 'medium',
      is_completed: false,
      category: 'personal',
    },
    {
      id: 3,
      user_id: 2,
      title: 'Prepare weekly meal plan',
      description: 'Plan dinners and create a grocery shopping list.',
      due_date: '2025-01-07',
      priority: 'low',
      is_completed: true,
      category: 'personal',
    },
    {
      id: 4,
      user_id: 2,
      title: 'Team performance review',
      description: 'Complete quarterly report for direct reports.',
      due_date: '2025-01-12',
      priority: 'high',
      is_completed: false,
      category: 'work',
    },
    {
      id: 5,
      user_id: 3,
      title: 'Study for math exam',
      description: 'Revise algebra and geometry chapters.',
      due_date: '2025-01-09',
      priority: 'high',
      is_completed: false,
      category: 'personal',
    },
    {
      id: 6,
      user_id: 3,
      title: 'Group science project',
      description: 'Prepare slides and practice presentation.',
      due_date: '2025-01-14',
      priority: 'medium',
      is_completed: false,
      category: 'work',
    },
    {
      id: 7,
      user_id: 4,
      title: 'Clean bedroom',
      description: 'Tidy desk, vacuum floor, and organise bookshelf.',
      due_date: '2025-01-06',
      priority: 'low',
      is_completed: true,
      category: 'personal',
    },
    {
      id: 8,
      user_id: 4,
      title: 'Finish homework',
      description: 'Complete English and history assignments.',
      due_date: '2025-01-08',
      priority: 'high',
      is_completed: false,
      category: 'work',
    },
    {
      id: 9,
      user_id: 1,
      title: 'Update website content',
      description: 'Refresh homepage copy and fix broken links.',
      due_date: '2025-01-11',
      priority: 'medium',
      is_completed: false,
      category: 'work',
    },
    {
      id: 10,
      user_id: 2,
      title: 'Yoga session',
      description: 'Attend evening vinyasa class.',
      due_date: '2025-01-10',
      priority: 'low',
      is_completed: false,
      category: 'personal',
    },
  ];
}
